// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Voice

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CityLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_CityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CityLabel, -350 );
lv_obj_set_y( ui_CityLabel, -189 );
lv_obj_set_align( ui_CityLabel, LV_ALIGN_CENTER );

ui_TempHighLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TempHighLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHighLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempHighLable, -260 );
lv_obj_set_y( ui_TempHighLable, -186 );
lv_obj_set_align( ui_TempHighLable, LV_ALIGN_CENTER );

ui_TempLowLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TempLowLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempLowLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempLowLable, -178 );
lv_obj_set_y( ui_TempLowLable, -187 );
lv_obj_set_align( ui_TempLowLable, LV_ALIGN_CENTER );

ui_FanSlider = lv_slider_create(ui_Screen1);
lv_obj_set_width( ui_FanSlider, 207);
lv_obj_set_height( ui_FanSlider, 21);
lv_obj_set_x( ui_FanSlider, -217 );
lv_obj_set_y( ui_FanSlider, 93 );
lv_obj_set_align( ui_FanSlider, LV_ALIGN_CENTER );


ui_FanLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_FanLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FanLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FanLable, -335 );
lv_obj_set_y( ui_FanLable, 49 );
lv_obj_set_align( ui_FanLable, LV_ALIGN_CENTER );

ui_LightLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LightLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightLable, -325 );
lv_obj_set_y( ui_LightLable, 161 );
lv_obj_set_align( ui_LightLable, LV_ALIGN_CENTER );

ui_CityDisplayLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_CityDisplayLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CityDisplayLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CityDisplayLable, -347 );
lv_obj_set_y( ui_CityDisplayLable, -118 );
lv_obj_set_align( ui_CityDisplayLable, LV_ALIGN_CENTER );

ui_TempLowDisplayLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TempLowDisplayLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempLowDisplayLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempLowDisplayLable, -178 );
lv_obj_set_y( ui_TempLowDisplayLable, -115 );
lv_obj_set_align( ui_TempLowDisplayLable, LV_ALIGN_CENTER );

ui_TempHighDisplayLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TempHighDisplayLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHighDisplayLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempHighDisplayLable, -259 );
lv_obj_set_y( ui_TempHighDisplayLable, -118 );
lv_obj_set_align( ui_TempHighDisplayLable, LV_ALIGN_CENTER );

ui_Request = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_Request, 373);
lv_obj_set_height( ui_Request, 132);
lv_obj_set_x( ui_Request, 177 );
lv_obj_set_y( ui_Request, -151 );
lv_obj_set_align( ui_Request, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_Request,"Placeholder...");



ui_TextArea1 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea1, 373);
lv_obj_set_height( ui_TextArea1, 205);
lv_obj_set_x( ui_TextArea1, 177 );
lv_obj_set_y( ui_TextArea1, 86 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");



ui_Switch1 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch1, 60);
lv_obj_set_height( ui_Switch1, 36);
lv_obj_set_x( ui_Switch1, -236 );
lv_obj_set_y( ui_Switch1, 161 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );


ui_PressRecord = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_PressRecord, 100);
lv_obj_set_height( ui_PressRecord, 50);
lv_obj_set_x( ui_PressRecord, 170 );
lv_obj_set_y( ui_PressRecord, -51 );
lv_obj_set_align( ui_PressRecord, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PressRecord, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PressRecord, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeatherDayLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_WeatherDayLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherDayLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherDayLable, -259 );
lv_obj_set_y( ui_WeatherDayLable, -11 );
lv_obj_set_align( ui_WeatherDayLable, LV_ALIGN_CENTER );

ui_WeatherNightLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_WeatherNightLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherNightLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherNightLable, -92 );
lv_obj_set_y( ui_WeatherNightLable, -115 );
lv_obj_set_align( ui_WeatherNightLable, LV_ALIGN_CENTER );

ui_WindSpeedLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_WindSpeedLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WindSpeedLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WindSpeedLable, -347 );
lv_obj_set_y( ui_WindSpeedLable, -11 );
lv_obj_set_align( ui_WindSpeedLable, LV_ALIGN_CENTER );

ui_WindSpeedDisplayLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_WindSpeedDisplayLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WindSpeedDisplayLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WindSpeedDisplayLable, -347 );
lv_obj_set_y( ui_WindSpeedDisplayLable, -58 );
lv_obj_set_align( ui_WindSpeedDisplayLable, LV_ALIGN_CENTER );

ui_WeatherDayDisplayLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_WeatherDayDisplayLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherDayDisplayLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherDayDisplayLable, -259 );
lv_obj_set_y( ui_WeatherDayDisplayLable, -58 );
lv_obj_set_align( ui_WeatherDayDisplayLable, LV_ALIGN_CENTER );

ui_WeatherNightDisplayLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_WeatherNightDisplayLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherNightDisplayLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherNightDisplayLable, -94 );
lv_obj_set_y( ui_WeatherNightDisplayLable, -187 );
lv_obj_set_align( ui_WeatherNightDisplayLable, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_PressRecord, ui_event_PressRecord, LV_EVENT_ALL, NULL);

}
