// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Voice

#ifndef _VOICE_UI_H
#define _VOICE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// #include "espnowTask.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_RecordLable;
extern lv_obj_t *ui_CityLabel;
extern lv_obj_t *ui_TempHighLable;
extern lv_obj_t *ui_TempLowLable;
extern lv_obj_t *ui_FanSlider;
extern lv_obj_t *ui_FanLable;
extern lv_obj_t *ui_LightLable;
extern lv_obj_t *ui_CityDisplayLable;
extern lv_obj_t *ui_TempLowDisplayLable;
extern lv_obj_t *ui_TempHighDisplayLable;
extern lv_obj_t *ui_Request;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_PressRecord;
extern lv_obj_t *ui_WeatherDayLable;
extern lv_obj_t *ui_WeatherNightLable;
extern lv_obj_t *ui_WindSpeedLable;
extern lv_obj_t *ui_WindSpeedDisplayLable;
extern lv_obj_t *ui_WeatherDayDisplayLable;
extern lv_obj_t *ui_WeatherNightDisplayLable;
extern lv_obj_t *ui____initial_actions0;
void ui_event_Switch1( lv_event_t * e);
void ui_event_FanSlider( lv_event_t * e);
void ui_event_PressRecord( lv_event_t * e);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
