// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Voice

#include "ui.h"
#include "ui_helpers.h"


// ///////////////////// FUNCTIONS ////////////////////
// void ui_event_Switch1( lv_event_t * e) {
//     lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
// if ( event_code == LV_EVENT_CLICKED) {
//     //   _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);


// }
// }

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_CityLabel;
lv_obj_t *ui_TempHighLable;
lv_obj_t *ui_TempLowLable;
lv_obj_t *ui_FanSlider;
lv_obj_t *ui_FanLable;
lv_obj_t *ui_LightLable;
lv_obj_t *ui_CityDisplayLable;
lv_obj_t *ui_TempLowDisplayLable;
lv_obj_t *ui_TempHighDisplayLable;
lv_obj_t *ui_Request;
lv_obj_t *ui_TextArea1;
lv_obj_t *ui_Switch1;
lv_obj_t *ui_PressRecord;
lv_obj_t *ui_RecordLable;
lv_obj_t *ui_WeatherDayLable;
lv_obj_t *ui_WeatherNightLable;
lv_obj_t *ui_WindSpeedLable;
lv_obj_t *ui_WindSpeedDisplayLable;
lv_obj_t *ui_WeatherDayDisplayLable;
lv_obj_t *ui_WeatherNightDisplayLable;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
bool Switch1_cliked = 0;
bool Switch2_cliked = 0,recordkey=0;
///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    Switch1_cliked = 1;
    //   _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    
}
}


void ui_event_FanSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    Switch2_cliked = 1;
    //   _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    
}
}


void ui_event_PressRecord( lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    recordkey = 1;
    //   _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}



///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
